[package]
name = "markdown-view"
version = "0.1.1"
description = "A Markdown editor with split view"
authors = ["you"]
edition = "2021"

[lib]
name = "markdown_view_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ctrlc = "3"
